"""
Export the assets for the episode-04 Metric Lab (../video/ep04-lab-assets.js):
the feature network's weights and five pools of 600 images to mix a "model" from.

    python export_ep04_lab.py
"""
import base64
import json
import os

import numpy as np

import evals as E
from vae import decode, load_mnist

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'video', 'ep04-lab-assets.js')
N = 600


def f16(a):
    a = np.ascontiguousarray(a, np.float32)
    return {'shape': list(a.shape), 'f16': base64.b64encode(a.astype('<f2').tobytes()).decode()}


def u8(imgs):
    return base64.b64encode(np.clip(np.round(imgs * 255), 0, 255).astype(np.uint8).tobytes()).decode()


def main():
    Xtr, ytr = load_mnist('train'); Xte, yte = load_mnist('test')
    clf = E.load_classifier(Xtr, ytr)
    rng = np.random.default_rng(0); perm = rng.permutation(len(Xte))
    pools = {
        'ref': Xte[perm[:N]],                                   # the real data every metric compares against
        'new': Xte[perm[N:2 * N]],                              # genuinely new, real digits (a perfect model)
        'train': Xtr[rng.permutation(len(Xtr))[:N]],            # the 'training set' copies come from
        'ones': Xtr[np.where(ytr == 1)[0][:N]],
        'vae': decode(E.load_vae(), rng.standard_normal((N, 2)).astype(np.float32)),
    }
    assets = {'net': {k: f16(v) for k, v in clf.items()}, 'pools': {k: u8(v) for k, v in pools.items()}, 'N': N}
    with open(OUT, 'w') as f:
        f.write('// Generated by code/export_ep04_lab.py — feature net + image pools for the Metric Lab.\n')
        f.write('window.LAB = ' + json.dumps(assets, separators=(',', ':')) + ';\n')
    print(f'wrote {OUT} ({os.path.getsize(OUT) / 1e6:.1f} MB)')


if __name__ == '__main__':
    main()
