"""
Compute every number shown in episode 04 and export it to ../video/episodes/ep04-assets.js.

    python export/export_ep04_assets.py        # a few minutes; reuses the cached VAE and feature net
"""
import base64
import json
import os

import numpy as np

from common import DATA, EPISODES, LABS, VIDEO  # noqa: E402,F401  (first: puts code/ on the path)
import evals as E
from vae import load_mnist

OUT = os.path.join(EPISODES, 'ep04-assets.js')


def u8(imgs):
    return base64.b64encode(np.clip(np.round(np.asarray(imgs) * 255), 0, 255).astype(np.uint8).tobytes()).decode()


def shift(img, dx, dy):
    a = img.reshape(28, 28)
    return np.roll(np.roll(a, dy, 0), dx, 1).reshape(784)


def main():
    rows, sets, clf, acc = E.scorecard(verbose=True)
    Xtr, ytr = load_mnist('train')
    Xte, yte = load_mnist('test')
    rng = np.random.default_rng(1)
    perm = np.random.default_rng(0).permutation(len(Xte))
    ref = Xte[perm[:E.N]]
    f_ref = E.features(clf, ref)

    # 2-D view of the 64-d feature space (PCA fitted on real data)
    mu = f_ref.mean(0)
    _, _, Vt = np.linalg.svd(f_ref - mu, full_matrices=False)
    proj = lambda F: np.round((F - mu) @ Vt[:2].T, 2).tolist()
    pca = {'ref': proj(f_ref[:500])}
    for k, X in sets.items():
        pca[k] = proj(E.features(clf, X[:500]))

    # class histograms p(y) and example p(y|x)
    py = {k: np.round(E.class_probs(clf, X).mean(0), 4).tolist() for k, X in sets.items()}
    pr = E.class_probs(clf, sets['real'][:200]); pv = E.class_probs(clf, sets['vae'][:200])
    ent = lambda p: -(p * np.log(p + 1e-12)).sum(1)
    i_sharp, i_amb = int(ent(pr).argmin()), int(ent(pv).argmax())
    examples = {'sharpImg': u8(sets['real'][i_sharp]), 'sharp': np.round(pr[i_sharp], 3).tolist(),
                'ambImg': u8(sets['vae'][i_amb]), 'amb': np.round(pv[i_amb], 3).tolist()}

    # pixels vs features: a digit, the same digit shifted 3 px, another 7, and a 1
    a = Xte[0]; b = shift(a, 3, 0)
    other7 = Xte[np.where(yte == 7)[0][5]]; one = Xte[np.where(yte == 1)[0][0]]
    fa = E.features(clf, np.stack([a, b, other7, one]))
    pix = lambda u, v: float(np.linalg.norm(u - v))
    percept = {'imgs': u8([a, b, other7, one]),
               'pixel': [pix(a, b), pix(a, other7), pix(a, one)],
               'feature': [pix(fa[0], fa[1]), pix(fa[0], fa[2]), pix(fa[0], fa[3])]}

    # novelty: nearest training neighbour of a few samples, and distance distributions
    def nn(Xs):
        d, idx = np.full(len(Xs), np.inf), np.zeros(len(Xs), int)
        for i in range(0, len(Xtr), 10000):
            D = E._pdist(Xs, Xtr[i:i + 10000]); j = D.argmin(1); v = D[np.arange(len(Xs)), j]
            better = v < d; d[better] = v[better]; idx[better] = j[better] + i
        return d, idx
    dists = {}
    for k in ('real', 'vae', 'copier'):
        d, _ = nn(sets[k][:300]); dists[k] = np.round(d, 2).tolist()
    pairs = {}
    for k in ('real', 'vae', 'copier'):
        d, idx = nn(sets[k][:4]); pairs[k] = {'s': u8(sets[k][:4]), 'n': u8(Xtr[idx]), 'd': np.round(d, 2).tolist()}

    assets = {
        'rows': rows, 'featAcc': acc,
        'samples': {k: u8(X[:16]) for k, X in sets.items()},
        'pca': pca, 'py': py, 'examples': examples, 'percept': percept,
        'nnDist': dists, 'nnPairs': pairs,
        'sevens': u8(Xte[np.where(yte == 7)[0][:8]]),
    }
    d = np.load(os.path.join(DATA, 'ep03_vae.npz'), allow_pickle=True)
    last = list(d['history'])[-1]
    assets['vaeTest'] = {'recon': float(last['test_recon']), 'kl': float(last['test_kl'])}
    with open(OUT, 'w') as f:
        f.write('// Generated by code/export_ep04_assets.py — every number in episode 04, computed on real models.\n')
        f.write('window.EP4 = ' + json.dumps(assets, separators=(',', ':')) + ';\n')
    print(f'wrote {OUT} ({os.path.getsize(OUT) / 1e3:.0f} kB)')
    print('percept', percept['pixel'], percept['feature'])
    print('nn medians', {k: float(np.median(v)) for k, v in dists.items()})


if __name__ == '__main__':
    main()
