"""
Train the flows shown in episode 06 and export everything to ../video/episodes/ep06-assets.js:
layer-by-layer positions (both directions), warped grid lines, exact density maps,
training curves and a worked log-likelihood breakdown.

    python export/export_ep06_assets.py        # a few minutes; trained flows are cached in data/
"""
import base64
import json
import os
import pickle

import numpy as np

from common import DATA, EPISODES, LABS, VIDEO  # noqa: E402,F401  (first: puts code/ on the path)
import flow as FL

OUT = os.path.join(EPISODES, 'ep06-assets.js')
R = 3.5


def trained(name, data, layers, steps, seed=0):
    path = os.path.join(DATA, f'ep06_{name}.pkl')
    if os.path.exists(path):
        return pickle.load(open(path, 'rb'))
    f, hist, nll, gauss = FL.train(data, layers, steps, seed=seed)
    res = {'flow': f, 'hist': hist, 'nll': nll, 'gauss': gauss}
    pickle.dump(res, open(path, 'wb'))
    return res


def density(f, n=96):
    g = np.linspace(-R, R, n, dtype=np.float32)
    X, Y = np.meshgrid(g, g[::-1])
    p = np.exp(f.log_prob(np.stack([X.ravel(), Y.ravel()], 1))).reshape(n, n)
    mx = float(p.max())
    return {'n': n, 'max': mx, 'u8': base64.b64encode(np.clip(np.round(np.sqrt(p / mx) * 255), 0, 255).astype(np.uint8).tobytes()).decode()}


def rnd(a, d=2):
    return np.round(np.asarray(a, dtype=np.float64), d).tolist()


def grid_lines(f, n=13, m=60):
    """Lines of the noise grid, pushed through the inverse flow one layer at a time."""
    g = np.linspace(-2.6, 2.6, n, dtype=np.float32); t = np.linspace(-2.6, 2.6, m, dtype=np.float32)
    pts = np.concatenate([np.stack([np.full(m, v), t], 1) for v in g] + [np.stack([t, np.full(m, v)], 1) for v in g])
    _, stages = f.inverse(pts, keep=True)
    return {'n': 2 * n, 'm': m, 'stages': [rnd(s) for s in stages]}


def main():
    moons = trained('moons', 'moons', 8, 5000)
    ring = trained('ring', 'ring', 8, 12000, seed=1)
    shallow = trained('shallow', 'moons', 2, 4000)
    f = moons['flow']
    rng = np.random.default_rng(3)
    x = FL.moons(500, rng)
    _, _, fwd = f.forward(x, keep=True)
    z = rng.standard_normal((700, 2)).astype(np.float32)
    _, inv = f.inverse(z, keep=True)
    # a worked example: one point on the moons, one far away
    ex = {}
    for name, pt in (('on', [[-0.75, 1.1]]), ('off', [[0.0, 1.6]])):
        p = np.array(pt, np.float32); zz, ld, _ = f.forward(p)
        ex[name] = {'x': pt[0], 'z': rnd(zz[0], 3), 'logN': float(-0.5 * (zz ** 2).sum() - FL.LOG2PI), 'logdet': float(ld[0]), 'logp': float(f.log_prob(p)[0])}
    zr, _ = ring['flow'].inverse(np.random.default_rng(4).standard_normal((1500, 2)).astype(np.float32))
    assets = {
        'R': R, 'layers': len(f.nets),
        'fwd': [rnd(s) for s in fwd], 'inv': [rnd(s) for s in inv], 'grid': grid_lines(f),
        'dens': density(f), 'densRing': density(ring['flow']), 'densShallow': density(shallow['flow']),
        'ringSamples': rnd(zr),
        'hist': rnd(moons['hist'], 3), 'nll': moons['nll'], 'gauss': moons['gauss'],
        'nllRing': ring['nll'], 'gaussRing': ring['gauss'], 'nllShallow': shallow['nll'],
        'example': ex,
    }
    with open(OUT, 'w') as fh:
        fh.write('// Generated by code/export_ep06_assets.py — real trained flows for episode 06.\n')
        fh.write('window.EP6 = ' + json.dumps(assets, separators=(',', ':')) + ';\n')
    print(f'wrote {OUT} ({os.path.getsize(OUT) / 1e6:.2f} MB)')
    print('example', ex)


if __name__ == '__main__':
    main()
