"""
Train the noise-conditional score networks shown in episode 08 and export ../video/episodes/ep08-assets.js:
the arrow field during training, the learned field at every noise level, where the small-noise field
is wrong, plain vs annealed Langevin paths, and the 80/20 weights experiment.

    python export/export_ep08_assets.py        # about a minute; trained nets are cached in data/
"""
import base64
import json
import os
import pickle

import numpy as np

from common import DATA, EPISODES, LABS, VIDEO  # noqa: E402,F401  (first: puts code/ on the path)
import score as SC

OUT = os.path.join(EPISODES, 'ep08-assets.js')
SNAPS = (1, 60, 200, 600, 2000, 6000)


def rnd(a, d=2):
    return np.round(np.asarray(a, dtype=np.float64), d).tolist()


def trained(name):
    path = os.path.join(DATA, f'ep08_{name}.pkl')
    if os.path.exists(path):
        return pickle.load(open(path, 'rb'))
    net, hist, snaps = SC.train(name, 6000, snap=SNAPS)
    res = {'net': net, 'hist': hist, 'snaps': snaps}
    os.makedirs(os.path.dirname(path), exist_ok=True); pickle.dump(res, open(path, 'wb'))
    return res


def with_params(P):
    n = SC.Net(); k = len(n.W); n.W, n.b = P[:k], P[k:]; return n


def grid(n=21, L=3.6):
    g = np.linspace(-L, L, n, dtype=np.float32); X, Y = np.meshgrid(g, g[::-1]); return np.stack([X.ravel(), Y.ravel()], 1)


def main():
    ring, two = trained('ring'), trained('twoblob'); net = ring['net']; S = SC.SIGMAS; mid = 4
    G = grid()
    fields = [rnd(net.score(G, s) * s, 3) for s in S]          # σ·s = the network's own output (≈ −ε): same scale at every level
    snaps = [rnd(with_params(ring['snaps'][k])(G, S[mid]), 3) for k in SNAPS]
    h = np.array(ring['hist']); k = len(h) // 150; hist = rnd(h[:k * 150].reshape(150, k).mean(1), 3)
    # where is the small-noise field wrong?
    E = grid(64, 3.6); s0 = S[-1]; t = SC.true_score('ring', E, s0)
    err = np.linalg.norm(net.score(E, s0) - t, axis=1) / (np.linalg.norm(t, axis=1) + 1e-6)
    errmap = base64.b64encode(np.clip(np.round(np.clip(err, 0, 1) * 255), 0, 255).astype(np.uint8).tobytes()).decode()
    # plain vs annealed Langevin, same start
    rng = np.random.default_rng(5); x0 = rng.uniform(-3.8, 3.8, (420, 2)).astype(np.float32)
    _, plain = SC.langevin(lambda x: net.score(x, s0), x0, 300, 0.1 * s0 * s0, np.random.default_rng(6), keep=5)
    _, ann = SC.annealed(net, x0, np.random.default_rng(6), keep=5)
    # the 80/20 experiment, with many particles for honest numbers
    tn = two['net']; y0 = np.random.default_rng(7).uniform(-3.8, 3.8, (4000, 2)).astype(np.float32)
    yp = SC.langevin(lambda x: tn.score(x, s0), y0, 300, 0.1 * s0 * s0, np.random.default_rng(8))
    ya = SC.annealed(tn, y0, np.random.default_rng(8))
    yl = SC.langevin(lambda x: tn.score(x, s0), y0, 3000, 0.1 * s0 * s0, np.random.default_rng(13))
    test = np.random.default_rng(3).uniform(-3, 3, (4000, 2)).astype(np.float32)
    rel = {f'{s:.2f}': float(np.median(np.linalg.norm(net.score(test, s) - SC.true_score('ring', test, s), axis=1) / (np.linalg.norm(SC.true_score('ring', test, s), axis=1) + 1e-9))) for s in (S[0], S[mid], S[-1])}
    A = {
        'R': SC.R, 'sigmas': rnd(S, 4), 'mid': mid, 'grid': {'n': 21, 'L': 3.6},
        'fields': fields, 'snaps': snaps, 'snapSteps': list(SNAPS), 'hist': hist,
        'err': {'n': 64, 'L': 3.6, 'u8': errmap}, 'relErr': rel,
        'data': rnd(SC.sample('ring', 400, np.random.default_rng(11))),
        'plain': [rnd(s) for s in plain], 'ann': [rnd(s) for s in ann], 'T': 30, 'keep': 5,
        'two': {'mu': SC.mixture('twoblob')[0].tolist(), 'w': SC.mixture('twoblob')[1].tolist(), 'std': 0.35,
                'plain': rnd(yp[:700]), 'ann': rnd(ya[:700]), 'plainShare': SC.left_share(yp), 'annShare': SC.left_share(ya), 'longShare': SC.left_share(yl),
                'data': rnd(SC.sample('twoblob', 700, np.random.default_rng(12)))},
    }
    with open(OUT, 'w') as fh:
        fh.write('// Generated by code/export_ep08_assets.py — real noise-conditional score networks for episode 08.\n')
        fh.write('window.EP8 = ' + json.dumps(A, separators=(',', ':')) + ';\n')
    print(f'wrote {OUT} ({os.path.getsize(OUT) / 1e6:.2f} MB)')
    print('relative error', {k_: round(v, 2) for k_, v in rel.items()}, '  80/20 shares: plain', round(A['two']['plainShare'], 3), 'annealed', round(A['two']['annShare'], 3))


if __name__ == '__main__':
    main()
