"""
Train everything shown in episode 05 and export it to ../video/episodes/ep05-assets.js:
  * a healthy 2-D GAN on 8 Gaussians (snapshots of samples, the judge's field, gradients)
  * a mode-hopping 2-D GAN (fast forger, slow judge)
  * an MNIST GAN (samples from fixed noise after every epoch) — scored with episode 04's judges

    python export/export_ep05_assets.py        # ~15 minutes on a laptop CPU (the MNIST GAN is cached)
"""
import base64
import json
import os
import pickle

import numpy as np

from common import DATA, EPISODES, LABS, VIDEO  # noqa: E402,F401  (first: puts code/ on the path)
import evals as E
import gan
from vae import decode, load_mnist

OUT = os.path.join(EPISODES, 'ep05-assets.js')


def u8(imgs):
    return base64.b64encode(np.clip(np.round(np.asarray(imgs) * 255), 0, 255).astype(np.uint8).tobytes()).decode()


def pack2d(snaps, every=1):
    out = []
    for s in snaps[::every]:
        out.append({'step': s['step'], 'modes': s['modes'], 'on': round(s['on'], 3),
                    'x': np.round(s['x'][:400], 2).tolist(),
                    'f': base64.b64encode(np.clip(np.round(s['field'] * 255), 0, 255).astype(np.uint8).tobytes()).decode(),
                    'g': np.round(s['grad'][:40], 3).tolist()})
    return out


def mnist_gan(epochs=40):
    path = os.path.join(DATA, 'ep05_gan.pkl')
    if os.path.exists(path):
        return pickle.load(open(path, 'rb'))
    G, D, snaps, hist = gan.train_mnist(epochs)
    res = {'G': G.P, 'snaps': snaps, 'hist': hist}
    pickle.dump(res, open(path, 'wb'))
    return res


def main():
    print('2-D: healthy run'); _, _, healthy = gan.train_2d(steps=5000, seed=3)
    print('2-D: fast forger, slow judge'); _, _, hop = gan.train_2d(steps=5000, seed=0, lr_g=3e-3, lr_d=1e-4)
    print('MNIST GAN'); res = mnist_gan()
    G = gan.MLP([('lin', 64, 256), 'lrelu', ('lin', 256, 512), 'lrelu', ('lin', 512, 784), 'sigmoid'], np.random.default_rng(0))
    G.P = res['G']
    Xs = gan.sample(G, E.N, seed=5)

    # score with episode 04's judges (same reference split as evals.py)
    Xtr, ytr = load_mnist('train'); Xte, yte = load_mnist('test')
    clf = E.load_classifier(Xtr, ytr)
    perm = np.random.default_rng(0).permutation(len(Xte)); ref = Xte[perm[:E.N]]
    f_ref, f = E.features(clf, ref), E.features(clf, Xs)
    p, r = E.precision_recall(f_ref, f)
    score = {'IS': E.inception_score(E.class_probs(clf, Xs)), 'FID': E.fid(f_ref, f), 'precision': p, 'recall': r,
             'NN_train': E.nn_train_distance(Xs, Xtr), 'C2ST': E.c2st(f_ref, f)}
    print('GAN scorecard', score)
    vae = decode(E.load_vae(), np.random.default_rng(5).standard_normal((16, 2)).astype(np.float32))
    assets = {
        'healthy': pack2d(healthy), 'hop': pack2d(hop),
        'mnistSnaps': [u8(s) for s in res['snaps']], 'mnistHist': res['hist'],
        'gan64': u8(gan.sample(G, 64, seed=9)), 'vae16': u8(vae),
        'score': score, 'ep4': json.load(open(os.path.join(DATA, 'ep04_rows.json'))) if os.path.exists(os.path.join(DATA, 'ep04_rows.json')) else None,
    }
    with open(OUT, 'w') as fh:
        fh.write('// Generated by code/export_ep05_assets.py — real GAN training runs for episode 05.\n')
        fh.write('window.EP5 = ' + json.dumps(assets, separators=(',', ':'), default=float) + ';\n')
    print(f'wrote {OUT} ({os.path.getsize(OUT) / 1e6:.1f} MB)')


if __name__ == '__main__':
    main()
