"""
The cold open of episode 01 is a trailer for the whole season, made only from the season's real models:

    names      typed by the episode-02 counting model (ar_counting.py, 3 letters of context)
    vae        a walk around the episode-03 VAE's latent space, decoded (vae.py)
    gan        episode 05's generator on MNIST, epoch by epoch (from ep05-assets.js)
    flow       episode 06's flow carrying noise onto the moons (from ep06-assets.js)
    ebm        episode 07's Langevin marbles rolling into the energy valleys (from ep07-assets.js)
    diffusion  episode 09's digits being denoised out of static (from ep09-assets.js)

→ ../video/episodes/ep01-assets.js   (export the other episodes first)

    python export/export_ep01_assets.py
"""
import base64
import json
import os
import random

import numpy as np

from common import DATA, EPISODES, LABS, VIDEO  # noqa: E402,F401  (first: puts code/ on the path)
import ar_counting as AR  # noqa: E402
from evals import load_vae  # noqa: E402
from vae import decode  # noqa: E402


def asset(n):
    s = open(os.path.join(EPISODES, f'ep{n:02d}-assets.js'), encoding='utf-8').read()
    return json.loads(s.split(' = ', 1)[1].rstrip().rstrip(';'))


def b64u8(a): return base64.b64encode(np.clip(np.round(np.asarray(a) * 255), 0, 255).astype(np.uint8).tobytes()).decode()
def b64sub(s, keep, n=784): u = base64.b64decode(s); return base64.b64encode(b''.join(u[i * n:(i + 1) * n] for i in keep)).decode()
def rnd(a, d=2): return np.round(np.asarray(a, np.float64), d).tolist()


def main():
    # episode 02: new names from the counting model (not copies of the training names)
    words = AR.load_words(); train = set(words); models = AR.build(words, 3); random.seed(4)
    names = []
    while len(names) < 6:
        w = AR.sample(models, 3)[0]
        if 4 <= len(w) <= 8 and w not in train and w not in names: names.append(w)
    # episode 03: the VAE's decoder along a loop through its latent space
    P = load_vae(); a = np.linspace(0, 2 * np.pi, 48, endpoint=False)
    z = np.stack([1.3 * np.cos(a) + 0.25 * np.sin(3 * a), 1.1 * np.sin(a)], 1).astype(np.float32)
    vae = b64u8(decode(P, z))
    # episode 05: nine of the generator's samples at a few epochs
    A5 = asset(5); epochs = [0, 1, 2, 4, 8, 16, 40]
    gan = [b64sub(A5['mnistSnaps'][e], range(9)) for e in epochs]
    # episode 06: 300 points carried from noise onto the moons (inverse pass, layer by layer)
    A6 = asset(6); flow = [rnd(st[:300]) for st in A6['inv']]
    # episode 07: 240 Langevin marbles and the energy landscape they roll on
    A7 = asset(7); ebm = {'R': A7['R'], 'E': A7['E'], 'lang': [rnd(st[:240]) for st in A7['lang']]}
    # episode 09: nine digits, every stage of the reverse process
    A9 = asset(9); diff = {'ts': A9['digits']['ts'], 'x': [b64sub(s, range(9)) for s in A9['digits']['x']]}
    E1 = {'names': names, 'vae': vae, 'gan': {'epochs': epochs, 'x': gan}, 'flow': flow, 'ebm': ebm, 'diffusion': diff}
    out = os.path.join(EPISODES, 'ep01-assets.js')
    with open(out, 'w') as fh:
        fh.write('// Generated by code/export/export_ep01_assets.py — the season trailer: real models from episodes 02–09.\n')
        fh.write('window.EP1 = ' + json.dumps(E1, separators=(',', ':')) + ';\n')
    print('names', names); print(os.path.basename(out), f'{os.path.getsize(out) / 1e6:.2f} MB')


if __name__ == '__main__':
    main()
