"""
Train the episode-03 autoencoder and VAE, then export what the video and playground need
(weights as float16, latent codes, sample images, training curves) to ../video/episodes/ep03-assets.js.

    python export/export_ep03_assets.py            # ~5 minutes on a laptop CPU
"""
import base64
import json
import os

import numpy as np

from common import DATA, EPISODES, LABS, VIDEO  # noqa: E402,F401  (first: puts code/ on the path)
from vae import encode, decode, load_mnist, train

OUT = os.path.join(EPISODES, 'ep03-assets.js')


def f16(a):
    a = np.ascontiguousarray(a, np.float32)
    return {'shape': list(a.shape), 'f16': base64.b64encode(a.astype('<f2').tobytes()).decode()}


def u8(imgs):
    return base64.b64encode(np.clip(np.round(imgs * 255), 0, 255).astype(np.uint8).tobytes()).decode()


def trained(model, epochs, beta=1.0):
    """Train once, then reuse the cached weights in data/."""
    path = os.path.join(DATA, f'ep03_{model}.npz')
    if os.path.exists(path):
        d = np.load(path, allow_pickle=True)
        return {k: d[k] for k in d.files if k != 'history'}, list(d['history'])
    P, hist = train(model, epochs, beta=beta, seed=0)
    np.savez(path, history=np.array(hist, dtype=object), **P)
    return P, hist


def main(epochs=30):
    ae, ae_hist = trained('ae', epochs)
    vae, vae_hist = trained('vae', epochs)
    Xte, yte = load_mnist('test')
    Xtr, ytr = load_mnist('train')
    n = 2500
    z_ae, _ = encode(ae, Xte[:n])
    mu, lv = encode(vae, Xte[:n])
    show = np.arange(24)                                   # the first 24 test digits
    ones = np.where(ytr == 1)[0][:16]
    assets = {
        'ae': {k: f16(ae[k]) for k in ('W1', 'b1', 'Wz', 'bz', 'W3', 'b3', 'W4', 'b4')},
        'vae': {k: f16(vae[k]) for k in ('W1', 'b1', 'Wmu', 'bmu', 'Wlv', 'blv', 'W3', 'b3', 'W4', 'b4')},
        'labels': yte[:n].tolist(),
        'zAE': np.round(z_ae, 3).tolist(),
        'zVAE': np.round(mu, 3).tolist(),
        'sigVAE': np.round(np.exp(0.5 * lv), 3).tolist(),
        'test': u8(Xte[show]), 'testLabels': yte[show].tolist(),
        'reconAE': u8(decode(ae, z_ae[show])), 'reconVAE': u8(decode(vae, mu[show])),
        'train': u8(Xtr[:32]), 'ones': u8(Xtr[ones]),
        'histAE': ae_hist, 'histVAE': vae_hist,
    }
    with open(OUT, 'w') as f:
        f.write('// Generated by code/export_ep03_assets.py — trained AE & VAE (2-D latent) on MNIST.\n')
        f.write('window.EP3 = ' + json.dumps(assets, separators=(',', ':')) + ';\n')
    print(f'wrote {OUT}  ({os.path.getsize(OUT) / 1e6:.1f} MB)')
    print('AE final', ae_hist[-1]); print('VAE final', vae_hist[-1])


if __name__ == '__main__':
    main()
